/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import optimizacion.Coordenada;
import optimizacion.Optimizacion;
import optimizacion.Variable;

/**
 *
 * @author Sergio
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    static int contador = 1;
    double num, ind, ind1;
    int con = 0, contRest = 0;
    double y;
    DefaultTableModel model;
    DefaultTableModel modelRest;
    ArrayList<Restriccion> rest = new ArrayList<Restriccion>();
    ArrayList<Restriccion> despeje = new ArrayList<Restriccion>();
    ArrayList<Coordenada> coor = new ArrayList<Coordenada>();
    boolean elimino = false;
    TableColumnModel tcm;

    public Interfaz() {
        initComponents();
        this.desactivarPestanas();
        cargar();
        cargarRest();
        tcm = tablaRest.getColumnModel();
        this.setLocationRelativeTo(null);
        // setUpSportColumn(tablaRest,tablaRest.getColumnModel().getColumn(3));
        //this.getContentPane().setBackground(Color.white);

    }

    public void cargarDatos(int cont) {

        model.insertRow(con, new Object[]{});
        model.setValueAt("X" + cont, con, 0);
        model.setValueAt("variable " + cont, con, 1);

        con++;
    }

    public void cargar() {
        String data[][] = {};
        String col[] = {"Nombre", "Descripcion"};
        model = new DefaultTableModel(data, col);
        datos.setModel(model);
    }

    public void setUpSportColumn(JTable table,
            TableColumn sportColumn) {
        //Set up the editor for the sport cells.
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("<=");
        comboBox.addItem(">=");
        comboBox.addItem("=");

        sportColumn.setCellEditor(new DefaultCellEditor(comboBox));

        //Set up tool tips for the sport cells.
        DefaultTableCellRenderer renderer
                = new DefaultTableCellRenderer();
        renderer.setToolTipText("Click for combo box");
        sportColumn.setCellRenderer(renderer);
    }

    public void cargarDatosRest() {
        setUpSportColumn(tablaRest, tablaRest.getColumnModel().getColumn(tcm.getColumnCount() - 1));
        modelRest.insertRow(contRest, new Object[]{});
        for (int i = 0; i < tcm.getColumnCount(); i++) {
            modelRest.setValueAt(0, contRest, i);
        }
        modelRest.setValueAt("<=", contRest, tcm.getColumnCount() - 1);

    }

    public void cargarRest() {
        String data[][] = {};
        String col[] = {"X1", "X2", "B", "OPC"};
        modelRest = new DefaultTableModel(data, col);
        tablaRest.setModel(modelRest);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        grupo = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        jSeparator6 = new javax.swing.JSeparator();
        botonAdd1 = new javax.swing.JLabel();
        botonDelete1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaRest = new javax.swing.JTable();
        botonAdd = new javax.swing.JLabel();
        botonDelete = new javax.swing.JLabel();
        jPanelSimplex = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setText("Metodos de optimizacion programacion lineal");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Variables");

        datos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Descripcion"
            }
        ));
        jScrollPane3.setViewportView(datos);

        botonAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        botonAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAdd1MouseClicked(evt);
            }
        });

        botonDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        botonDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDelete1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28)
                        .addComponent(botonAdd1)
                        .addGap(18, 18, 18)
                        .addComponent(botonDelete1)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addComponent(jSeparator6))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdd1)
                    .addComponent(jLabel16)
                    .addComponent(botonDelete1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Descripcion del Problema");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nombre:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(166, 166, 166))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Restricciones");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tablaRest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tablaRest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaRest);

        botonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        botonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAddMouseClicked(evt);
            }
        });

        botonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        botonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(botonAdd)
                                .addGap(18, 18, 18)
                                .addComponent(botonDelete))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonDelete)
                    .addComponent(jLabel8))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );

        jTabbedPane1.addTab("Planteamiento", jPanel6);

        javax.swing.GroupLayout jPanelSimplexLayout = new javax.swing.GroupLayout(jPanelSimplex);
        jPanelSimplex.setLayout(jPanelSimplexLayout);
        jPanelSimplexLayout.setHorizontalGroup(
            jPanelSimplexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanelSimplexLayout.setVerticalGroup(
            jPanelSimplexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Metodo Simplex", jPanelSimplex);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tecnica de la M", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Precio Sombra", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Graficas", jPanel11);

        jToolBar2.setRollover(true);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abrir.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton6);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton1);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/adelante.png"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton8);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/graficar.png"))); // NOI18N
        jButton4.setText("Graficar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/solucion.png"))); // NOI18N
        jButton3.setText("Solucionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        for (int i = 0; i < tablaRest.getRowCount(); i++) {
            ArrayList<Variable> var = new ArrayList<Variable>();
            for (int j = 0; j < tablaRest.getColumnCount(); j++) {

                if (j == tablaRest.getColumnCount() - 1) {
                    if (modelRest.getValueAt(i, j).toString().equalsIgnoreCase("<=")) {
                        //  JOptionPane.showMessageDialog(null,modelRest.getValueAt(i, j).toString());
                        var.add(new Variable(modelRest.getColumnName(j), 1));

                    } else if (modelRest.getValueAt(i, j).toString().equalsIgnoreCase(">=")) {
                        var.add(new Variable(modelRest.getColumnName(j), 2));
                    } else if (modelRest.getValueAt(i, j).toString().equalsIgnoreCase("=")) {
                        var.add(new Variable(modelRest.getColumnName(j), 3));
                    }
                } else {
                    //     JOptionPane.showMessageDialog(null,modelRest.getValueAt(i, j).toString());
                    var.add(new Variable(modelRest.getColumnName(j), Double.parseDouble(modelRest.getValueAt(i, j).toString())));
                }

            }
            rest.add(new Restriccion(var));

        }
        despejarY();
    //combinaciones();
        //  for (int i = 0; i < coor.size(); i++) {
        //    JOptionPane.showMessageDialog(null, coor.get(i).getX()+ ","+coor.get(i).getY());
        //  }
    }//GEN-LAST:event_jButton4ActionPerformed

    public boolean existe(String fila, ArrayList<String> compa) {
        boolean esta = false;
        for (int i = 0; i < compa.size(); i++) {
            if (fila.equalsIgnoreCase(compa.get(i))) {
                esta = true;
                break;
            }
        }
        return esta;
    }
    public void activarPestanas(){
        this.jTabbedPane1.setEnabledAt(1, true);
        this.jTabbedPane1.setEnabledAt(2, true);
        this.jTabbedPane1.setEnabledAt(3, true);
        this.jTabbedPane1.setEnabledAt(4, true);
    }
    
    public void desactivarPestanas(){
        this.jTabbedPane1.setEnabledAt(1, false);
        this.jTabbedPane1.setEnabledAt(2, false);
        this.jTabbedPane1.setEnabledAt(3, false);
        this.jTabbedPane1.setEnabledAt(4, false);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //JOptionPane.showMessageDialog(null, modelRest.getValueAt(0, 1));
        this.activarPestanas();
        new Optimizacion().iteraciones();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdd1MouseClicked
        cargarDatos(contador);
        contador++;
        int pos1 = 0, pos2 = 0;
        ArrayList<String> compa = new ArrayList<String>();
        try {
           //TableColumn a=new TableColumn();

            for (int i = 0; i < tcm.getColumnCount(); i++) {
                compa.add(tcm.getColumn(i).getIdentifier().toString());
            }

            for (int i = 0; i < model.getRowCount(); i++) {
                if (!existe(model.getValueAt(i, 0).toString(), compa)) {
                    TableColumn a = new TableColumn();
                    a.setHeaderValue(model.getValueAt(model.getRowCount() - 1, 0));
                    tcm.addColumn(a);
                    //   modelRest.addColumn(model.getValueAt(model.getRowCount()-1, 0));
                    ArrayList<String> arreglo = new ArrayList<String>();
                    for (int n = 0; n < tcm.getColumnCount(); n++) {
                        if (tcm.getColumn(n).getIdentifier().toString().equalsIgnoreCase("b")) {
                            pos1 = n;
                        } else if (tcm.getColumn(n).getIdentifier().toString().equalsIgnoreCase("opc")) {
                            pos2 = n;
                        }
                        arreglo.add(tcm.getColumn(n).getIdentifier().toString());
                    }
                    int dis = tcm.getColumnCount() - pos2 - 1;
                    for (int p = 2; p <= dis + 1; p++) {
                        arreglo.set((tcm.getColumnCount() - 1) - p, tcm.getColumn(tcm.getColumnCount() - (p - 1)).getIdentifier().toString());
                    }

                    arreglo.set(pos1 + dis, "B");
                    arreglo.set(pos2 + dis, "OPC");
                    modelRest.setColumnIdentifiers(arreglo.toArray());

                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_botonAdd1MouseClicked

    private void botonDelete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDelete1MouseClicked

        elimino = true;
        model.removeRow(model.getRowCount() - 1);
        con--;
        contador--;
        int pos;
        for (int i = 0; i < tcm.getColumnCount() - 2 - (model.getRowCount()); i++) {
            pos = tcm.getColumnCount() - 3;

            TableColumn columnaABorrar = tcm.getColumn(pos);
            tablaRest.removeColumn(columnaABorrar);
            pos--;
        }

    }//GEN-LAST:event_botonDelete1MouseClicked

    private void botonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAddMouseClicked

        cargarDatosRest();

        contRest++;
    }//GEN-LAST:event_botonAddMouseClicked

    private void botonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeleteMouseClicked
        modelRest.removeRow(modelRest.getRowCount() - 1);
        contRest--;
    }//GEN-LAST:event_botonDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public void despejarY() {
        double opc;
        for (int i = 0; i < rest.size(); i++) {
            opc = rest.get(i).variable.get(3).getValor();
            ArrayList<Variable> var = new ArrayList<Variable>();
            if (rest.get(i).variable.get(0).getValor() != 0) {
                if (rest.get(i).variable.get(1).getValor() != 0) {
                    num = rest.get(i).variable.get(1).getValor() * -1;

                } else {
                    num = 0;
                }
            } else {
                num = 1;
            }

            if (rest.get(i).variable.get(0).getValor() != 0) {
                y = 1;
                ind = num / rest.get(i).variable.get(0).getValor();
                ind1 = rest.get(i).variable.get(2).getValor() / rest.get(i).variable.get(0).getValor();
            } else {
                y = 0;
                ind = num;
                ind1 = rest.get(i).variable.get(2).getValor() / rest.get(i).variable.get(1).getValor();
            }
            var.add(new Variable("X2", ind));
            var.add(new Variable("B", ind1));
            var.add(new Variable("OPC", opc));
            var.add(new Variable("X1", y));
            despeje.add(new Restriccion(var));

        }
        System.out.println(seleccionarPuntosValidos(encontrarInterseccion(despeje.get(0), despeje.get(1)), despeje));
        JOptionPane.showMessageDialog(null, encontrarInterseccion(despeje.get(0), despeje.get(1)).getX() + "," + encontrarInterseccion(despeje.get(0), despeje.get(1)).getY());
        // JOptionPane.showMessageDialog(null, encontrarInterseccion(despeje.get(0),despeje.get(1)).getY());
    }

    public Coordenada encontrarInterseccion(Restriccion a, Restriccion b) {
        double x, y;
        Coordenada nueva;
        if (a.variable.get(3).getValor() != 0 && b.variable.get(3).getValor() != 0) {
            x = (b.variable.get(1).getValor() - a.variable.get(1).getValor()) / (a.variable.get(0).getValor() - b.variable.get(0).getValor());
            y = a.variable.get(0).getValor() * x + a.variable.get(1).getValor();
            nueva = new Coordenada(x, y);
            return nueva;
        } else if (a.variable.get(3).getValor() != 0 && b.variable.get(3).getValor() == 0) {
            x = b.variable.get(1).getValor();
            y = a.variable.get(0).getValor() * x + a.variable.get(1).getValor();
            nueva = new Coordenada(x, y);
            return nueva;
        } else if (a.variable.get(3).getValor() == 0 && b.variable.get(3).getValor() != 0) {
            x = a.variable.get(1).getValor();
            y = b.variable.get(0).getValor() * x + b.variable.get(1).getValor();
            nueva = new Coordenada(x, y);
            return nueva;
        }
        x = 0;
        y = 0;
        nueva = new Coordenada(x, y);

        return nueva;

    }

    public Coordenada encontrarInterseccionejex(Restriccion a) {
        double x, y;
        Coordenada nueva;
        if (a.variable.get(3).getValor() != 0) {
            x = 0;
            y = a.variable.get(1).getValor();
            nueva = new Coordenada(x, y);
        } else {
            x = 0;
            y = 0;
            nueva = new Coordenada(x, y);
        }

        return nueva;

    }

    public boolean tieneSolucion(ArrayList<Coordenada> a) {
        boolean tiene = false;
        if (a.size() >= 3) {
            tiene = true;
        }
        return tiene;
    }

    public Coordenada encontrarInterseccionejey(Restriccion a) {
        double x, y;
        Coordenada nueva;
        if (a.variable.get(3).getValor() != 0) {
            x = -1 * (a.variable.get(1).getValor() / a.variable.get(0).getValor());
            y = 0;
            nueva = new Coordenada(x, y);
        } else {
            y = 0;
            x = a.variable.get(1).getValor();
            nueva = new Coordenada(x, y);
        }

        return nueva;

    }

    public void combinaciones() {
        int j = 0;
        for (int i = 0; i < despeje.size(); i++) {
            j = i;
            while (j < despeje.size() - 1) {

                j++;
                if (seleccionarPuntosValidos(encontrarInterseccion(despeje.get(i), despeje.get(j)), despeje)) {
                    coor.add(encontrarInterseccion(despeje.get(i), despeje.get(j)));
                }

                System.out.println("i:" + i);
                System.out.println("j:" + j);
            }
            j = 0;
        }
        for (int i = 0; i < despeje.size(); i++) {
            if (seleccionarPuntosValidos(encontrarInterseccionejex(despeje.get(i)), despeje)) {
                coor.add(encontrarInterseccionejex(despeje.get(i)));
            }
            if (seleccionarPuntosValidos(encontrarInterseccionejey(despeje.get(i)), despeje)) {
                coor.add(encontrarInterseccionejey(despeje.get(i)));
            }

        }
        if (tieneSolucion(coor)) {
            System.out.println("Tiene solucion");
        } else {
            System.out.println("No tiene solucion");
        }

    }

    public boolean seleccionarPuntosValidos(Coordenada validar, ArrayList<Restriccion> rest) {
        boolean entra = false;

        for (int i = 0; i < rest.size(); i++) {
            if (rest.get(i).variable.get(2).getValor() == 1) {

                if (validar.getY() <= (rest.get(i).variable.get(0).getValor() * validar.getX() + rest.get(i).variable.get(1).getValor()) && validar.getY() >= 0 && validar.getX() >= 0) {
                    JOptionPane.showMessageDialog(null, "si son ");
                    entra = true;
                } else {
                    break;
                }

            } else if (rest.get(i).variable.get(2).getValor() == 2) {
                if (validar.getY() >= (rest.get(i).variable.get(0).getValor() * validar.getX() + rest.get(i).variable.get(1).getValor()) && validar.getY() >= 0 && validar.getX() >= 0) {
                    entra = true;
                } else {
                    break;
                }
            } else if (rest.get(i).variable.get(2).getValor() == 3) {
                if (validar.getY() == (rest.get(i).variable.get(0).getValor() * validar.getX() + rest.get(i).variable.get(1).getValor()) && validar.getY() >= 0 && validar.getX() >= 0) {
                    entra = true;
                } else {
                    break;
                }
            }
        }
        return entra;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Interfaz().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonAdd;
    private javax.swing.JLabel botonAdd1;
    private javax.swing.JLabel botonDelete;
    private javax.swing.JLabel botonDelete1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable datos;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JPanel jPanelSimplex;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tablaRest;
    // End of variables declaration//GEN-END:variables
}
